services:
  api:
    build:
      context: .
      dockerfile: ./apps/workout-journal-api/Dockerfile.dev
    image: workout-journal-api:latest
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./apps/workout-journal-api:/usr/src/app/apps/workout-journal-api
      - ./libs:/usr/src/app/libs
    depends_on:
      - postgres

  worker:
    build:
      context: .
      dockerfile: ./apps/workout-journal-worker/Dockerfile.dev
    image: workout-journal-worker:latest
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./apps/workout-journal-worker:/usr/src/app/apps/workout-journal-worker
      - ./libs:/usr/src/app/libs
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: workout-postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
